# Generated by Django 5.2.5 on 2025-09-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='inportant',
            new_name='important',
        ),
    ]
